# Generated by Django 5.1.3 on 2024-11-05 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Введите действительный адрес электронной почты')])),
                ('tel', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message='Введите телефонный номер в формате +1234567890, максимум 15 цифр')])),
                ('massage', models.TextField(validators=[django.core.validators.MaxLengthValidator(500, message='Сообщение должно содержать не более 500 символов')])),
            ],
        ),
    ]
