# Generated by Django 5.1.3 on 2024-11-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Название')),
                ('image', models.ImageField(upload_to='img/%y-%m-%d', verbose_name='Изображение')),
                ('price', models.FloatField(verbose_name='Цена')),
            ],
        ),
    ]
