# Generated by Django 5.1.2 on 2024-11-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_productcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcard',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
